### ISSUE TITLE
puzzled in merging wait constrains operation

### ISSUE THREAD

**Issue by Benjamin-Miller1** [PathPlanning/Continuous-CBS#3] opened 2021-05-30 13:26 UTC
excuse me , i am reading your outstanding work.
i want to confirm if the following process exists mistake.
i think that only if one interval overlaps with the following one i.e.[i].second > [i+1].first, a merge operation can be performed.
```
    for(unsigned int i = 0; i + 1 < collision_intervals[id].size(); i++)
        if(collision_intervals[id][i].second - CN_EPSILON < collision_intervals[id][i+1].first)
        {
            collision_intervals[id][i].second = collision_intervals[id][i+1].second;
            collision_intervals[id].erase(collision_intervals[id].begin() + i + 1);
            i--;
        }
```

**Comment by aandreychuk** [comment] 2021-05-30 13:49
Yep, you are definitely right, I have fixed it. Thanks.

**Comment by Benjamin-Miller1** [comment] 2021-06-01 01:04
I am glad of your attention.
After modify the code, I get unexpected result due to timeout. I have no idea to solve this problem. Could you track it further more?

**Comment by aandreychuk** [comment] 2021-06-01 13:27
I've tried to reproduce the problem, but haven't found any difference in the algorithm's behavior after the bug fixing.
Can you share an example of an instance where you have troubles?

**Comment by Benjamin-Miller1** [comment] 2021-06-02 06:12
I tested the built-in example of roadmap without any change. And it shows the same result of timeout on both Windows and Linux.

**Comment by aandreychuk** [comment] 2021-06-03 10:12
Thanks. There was a really dumb bug with computing intervals for the goal state :) Now it is fixed.
It never happened before, because there always was only one big merged collision interval, but now there might be several of them. Nevertheless, it doesn't affect the solution quality, as we need to reach the goal after the last collision interval anyway.

**Closed as completed by aandreychuk** 2021-06-03 10:12 UTC
